import { pgTable, pgSchema, char, uuid, smallint, numeric, text, timestamp, boolean, integer, varchar, date, index, foreignKey } from "drizzle-orm/pg-core";
const e360 = pgSchema("e360");
import { sql } from "drizzle-orm";

export const projectmasterInE360 = e360.table("projectmaster", {
    projectid: integer()
        .default(sql`nextval('projectmaster_project_pkey_seq'::regclass)`)
        .primaryKey()
        .notNull(),
    customerid: integer().notNull(),
    comtenantid: integer().notNull(),
    companyid: integer().notNull(),
    businessunitid: integer(),
    servicelineid: integer(),
    departmentid: integer(),
    projecttypeid: integer().notNull(),
    datprojectbillingtypeid: integer().notNull(),
    projectname: varchar({ length: 250 }).notNull(),
    projectcode: varchar({ length: 20 }),
    projectdescription: varchar({ length: 5000 }),
    locationid: integer(),
    startdate: date().notNull(),
    enddate: date().notNull(),
    projectstatus: integer().notNull(),
    defaultcomcurrencyid: smallint().notNull(),
    totalestimateamt: numeric({ precision: 18, scale: 3 }).notNull(),
    totalactualamt: numeric({ precision: 18, scale: 3 }).notNull(),
    reasonforrejection: varchar({ length: 500 }),
    projectmanagerid: integer().notNull(),
    deliverymanagerid: integer().notNull(),
    isactiveflag: boolean().notNull(),
    createdtimestamp: timestamp({ mode: "string" }).notNull(),
    createdcomuserid: smallint().notNull(),
    modifiedtimestamp: timestamp({ mode: "string" }),
    modifiedcomuserid: smallint(),
    notes: varchar({ length: 100 }),
    custProject: boolean("cust_project").notNull(),
    category: char({ length: 1 }),
    billingcycle: varchar({ length: 50 }),
    deliverymodemasterid: integer(),
    licensingrevenue: boolean(),
    opportunityid: integer(),
    pmocontactpersonid: integer(),
    isSapproject: boolean("is_sapproject"),
    techgroupid: integer(),
    projectsubtype: varchar({ length: 250 }),
    pmo1: integer(),
    pmo2: integer(),
    pmo3: integer(),
    timetemplatemasterid: integer(),
    shiftstarttime: numeric({ precision: 12, scale: 2 }),
    shiftendtime: numeric({ precision: 12, scale: 2 }),
    timezone: varchar({ length: 100 }),
    commercialspaymentterm: varchar({ length: 50 }),
});
